/**
 * @fileoverview Issuing-body values for the body-filtered applications: Dsk and Pvak
 * (`EntscheidendeBehoerde` schema enums), Dok (exact match, 59 documented authorities),
 * Verg (term match, 4 procurement review bodies), and Avsv (`Urheber` exact match,
 * case-insensitive, no wildcards — social-insurance carriers). An Avsv designation ending in a
 * parenthesized abbreviation carries it as `abbreviation`, which the request builder expands to
 * the full value; RIS matches only the full value, never the bare abbreviation.
 * Sources: OGD request XSDs + OGD Handbook V2.6 value lists.
 * @module services/ris/reference/issuing-bodies
 */

/** One issuing-body filter value. */
export interface IssuingBody {
  /**
   * Avsv only: the parenthesized abbreviation the designation ends in ("ÖGK"), accepted as an
   * `issuer` input and expanded to `value`. Absent on every row without such a suffix.
   */
  readonly abbreviation?: string;
  /** RIS application the value applies to. */
  readonly application: 'Dsk' | 'Pvak' | 'Dok' | 'Verg' | 'Avsv';
  /** Usage note, when the value needs context. */
  readonly note: string | null;
  /** Upstream request parameter. */
  readonly parameter: 'EntscheidendeBehoerde' | 'Urheber';
  /** Exact upstream filter value. */
  readonly value: string;
}

/** All documented issuing-body values. */
export const RIS_ISSUING_BODIES = [
  {
    value: 'Datenschutzbehoerde',
    application: 'Dsk',
    parameter: 'EntscheidendeBehoerde',
    note: 'Data Protection Authority, decisions 2014 and later (schema enum — ASCII spelling, no umlaut)',
  },
  {
    value: 'Datenschutzkommission',
    application: 'Dsk',
    parameter: 'EntscheidendeBehoerde',
    note: 'Data Protection Commission, decisions up to 2013 (schema enum)',
  },
  {
    value: 'Personalvertretungsaufsichtsbehoerde',
    application: 'Pvak',
    parameter: 'EntscheidendeBehoerde',
    note: 'Staff-representation oversight authority, 2014 and later (schema enum)',
  },
  {
    value: 'PersonalvertretungsAufsichtskommission',
    application: 'Pvak',
    parameter: 'EntscheidendeBehoerde',
    note: 'Predecessor commission, up to 2013 (schema enum — note the inner capital A)',
  },
  {
    value: 'Bundesvergabeamt',
    application: 'Verg',
    parameter: 'EntscheidendeBehoerde',
    note: 'Procurement review body (term match)',
  },
  {
    value: 'Bundes-Vergabekontrollkommission',
    application: 'Verg',
    parameter: 'EntscheidendeBehoerde',
    note: 'Procurement review body (term match)',
  },
  {
    value: 'Vergabekontrollsenat Salzburg',
    application: 'Verg',
    parameter: 'EntscheidendeBehoerde',
    note: 'Procurement review body (term match)',
  },
  {
    value: 'Vergabekontrollsenat Wien',
    application: 'Verg',
    parameter: 'EntscheidendeBehoerde',
    note: 'Procurement review body (term match)',
  },
  {
    value: 'Bundesdisziplinarbehörde',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Parlamentsdirektion',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  { value: 'Rechnungshof', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  {
    value: 'Volksanwaltschaft',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Berufungskommission',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Disziplinaroberkommission',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Burgenland',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Kärnten',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Niederösterreich',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Oberösterreich',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Salzburg',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Steiermark',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Tirol',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Vorarlberg',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bildungsdirektion Wien',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  { value: 'Bundeskanzleramt', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  {
    value: 'BM für Arbeit, Familie und Jugend',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Arbeit, Soziales und Konsumentenschutz',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Arbeit, Soziales, Gesundheit und Konsumentenschutz',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Bildung und Frauen',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  { value: 'BM für Bildung', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  {
    value: 'BM für Bildung, Wissenschaft und Forschung',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Digitalisierung und Wirtschaftsstandort',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Europa, Integration und Äußeres',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für europäische und internationale Angelegenheiten',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Familien und Jugend',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  { value: 'BM für Finanzen', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  {
    value: 'BM für Gesundheit und Frauen',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Gesundheit',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  { value: 'BM für Inneres', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  { value: 'BM für Justiz', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  {
    value: 'BM für Klimaschutz, Umwelt, Energie, Mobilität, Innovation und Technologie',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Kunst, Kultur, öffentlichen Dienst und Sport',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Land- u. Forstwirtschaft, Umwelt und Wasserwirtschaft',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Landesverteidigung und Sport',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Landesverteidigung',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Landwirtschaft, Regionen und Tourismus',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Nachhaltigkeit und Tourismus',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für öffentlichen Dienst und Sport',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Soziales, Gesundheit, Pflege und Konsumentenschutz',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Unterricht, Kunst und Kultur',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Verfassung, Reformen, Deregulierung und Justiz',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Verkehr, Innovation und Technologie',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Wirtschaft, Familie und Jugend',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Wissenschaft und Forschung',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'BM für Wissenschaft, Forschung und Wirtschaft',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Bundesfinanzgericht',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  { value: 'Land Kärnten', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  { value: 'Land Salzburg', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  { value: 'Land Tirol', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  { value: 'Land Vorarlberg', application: 'Dok', parameter: 'EntscheidendeBehoerde', note: null },
  {
    value: 'Landesschulrat Burgenland',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Landesschulrat Niederösterreich',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Landesschulrat Oberösterreich',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Landesschulrat Steiermark',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Präsidentschaftskanzlei',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Stadtschulrat Wien',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Verfassungsgerichtshof',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Verwaltungsgerichtshof',
    application: 'Dok',
    parameter: 'EntscheidendeBehoerde',
    note: null,
  },
  {
    value: 'Österreichische Gesundheitskasse (ÖGK)',
    abbreviation: 'ÖGK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current carrier (2020 and later)',
  },
  {
    value: 'Sozialversicherungsanstalt der Selbständigen (SVS)',
    abbreviation: 'SVS',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current carrier (2020 and later)',
  },
  {
    value: 'Versicherungsanstalt öffentlich Bediensteter, Eisenbahnen und Bergbau (BVAEB)',
    abbreviation: 'BVAEB',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current carrier (2020 and later)',
  },
  {
    value: 'Allgemeine Unfallversicherungsanstalt (AUVA)',
    abbreviation: 'AUVA',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current carrier',
  },
  {
    value: 'Pensionsversicherungsanstalt (PVA)',
    abbreviation: 'PVA',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current carrier',
  },
  {
    value: 'Pensionsinstitut der Linz AG (PI Linz AG)',
    abbreviation: 'PI Linz AG',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current carrier',
  },
  {
    value: 'Dachverband der Sozialversicherungsträger (DVSV)',
    abbreviation: 'DVSV',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Current umbrella body (2020 and later); successor of HVSV',
  },
  { value: 'DVSV Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'ÖGK Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'SVS Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'BVAEB Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  {
    value: 'Bundesschiedskommission (BSK)',
    abbreviation: 'BSK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Wiener Gebietskrankenkasse (WGKK)',
    abbreviation: 'WGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Niederösterreichische Gebietskrankenkasse (NÖGKK)',
    abbreviation: 'NÖGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Burgenländische Gebietskrankenkasse (BGKK)',
    abbreviation: 'BGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Oberösterreichische Gebietskrankenkasse (OÖGKK)',
    abbreviation: 'OÖGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Steiermärkische Gebietskrankenkasse (STGKK)',
    abbreviation: 'STGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Kärntner Gebietskrankenkasse (KGKK)',
    abbreviation: 'KGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Salzburger Gebietskrankenkasse (SGKK)',
    abbreviation: 'SGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Tiroler Gebietskrankenkasse (TGKK)',
    abbreviation: 'TGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Vorarlberger Gebietskrankenkasse (VGKK)',
    abbreviation: 'VGKK',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into ÖGK in 2020',
  },
  {
    value: 'Sozialversicherungsanstalt der gewerblichen Wirtschaft (SVA)',
    abbreviation: 'SVA',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into SVS in 2020',
  },
  {
    value: 'Sozialversicherungsanstalt der Bauern (SVB)',
    abbreviation: 'SVB',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into SVS in 2020',
  },
  {
    value: 'Versicherungsanstalt öffentlich Bediensteter (BVA)',
    abbreviation: 'BVA',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into BVAEB in 2020',
  },
  {
    value: 'Versicherungsanstalt für Eisenbahnen und Bergbau (VAEB)',
    abbreviation: 'VAEB',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — merged into BVAEB in 2020',
  },
  {
    value: 'Hauptverband der österreichischen Sozialversicherungsträger (HVSV)',
    abbreviation: 'HVSV',
    application: 'Avsv',
    parameter: 'Urheber',
    note: 'Historical — succeeded by DVSV in 2020',
  },
  {
    value: 'Versicherungsanstalt des österreichischen Bergbaues',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Versicherungsanstalt der österreichischen Eisenbahnen',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Pensionsversicherungsanstalt der Angestellten',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Pensionsversicherungsanstalt der Arbeiter',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse der Wiener Verkehrsbetriebe (BKK-WVB)',
    abbreviation: 'BKK-WVB',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Mondi (BKK Mondi)',
    abbreviation: 'BKK Mondi',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse voestalpine Bahnsysteme (BKK-VA)',
    abbreviation: 'BKK-VA',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Zeltweg (BKK-ZW)',
    abbreviation: 'BKK-ZW',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Kapfenberg (BKK-KA)',
    abbreviation: 'BKK-KA',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Austria Tabak (BKK-AT)',
    abbreviation: 'BKK-AT',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Mondi Business Paper',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Neusiedler',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Betriebskrankenkasse Alpine Donawitz',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  { value: 'Betriebskrankenkasse Semperit', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'Betriebskrankenkasse Kindberg', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'Betriebskrankenkasse Pengg', application: 'Avsv', parameter: 'Urheber', note: null },
  {
    value: 'Pensionsinstitut für Verkehr und öffentliche Einrichtungen',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  { value: 'HVSV Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'Wiener Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  {
    value: 'Niederösterreichischer Gesamtvertrag',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Burgenländischer Gesamtvertrag',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Oberösterreichischer Gesamtvertrag',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  {
    value: 'Steiermärkischer Gesamtvertrag',
    application: 'Avsv',
    parameter: 'Urheber',
    note: null,
  },
  { value: 'Kärntner Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'Salzburger Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'Tiroler Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'Vorarlberger Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'SVA Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'SVB Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'BVA Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
  { value: 'VAEB Gesamtvertrag', application: 'Avsv', parameter: 'Urheber', note: null },
] as const satisfies readonly IssuingBody[];
